<?php

declare(strict_types=1);

namespace Plain\Tests\Integration;

use PHPUnit\Framework\TestCase;

class CodeGenerationTest extends TestCase
{
    private string $generatedPath;

    protected function setUp(): void
    {
        parent::setUp();
        $this->generatedPath = __DIR__ . '/../../src/Generated';
    }

    public function testGeneratedDirectoryExists(): void
    {
        $this->assertDirectoryExists($this->generatedPath, 'Generated directory should exist');
    }

    public function testGeneratedFilesExist(): void
    {
        if (!is_dir($this->generatedPath)) {
            $this->markTestSkipped('Generated directory does not exist. Run: php generate.php');
        }

        $files = glob($this->generatedPath . '/*.php');

        $this->assertNotEmpty($files, 'Generated directory should contain PHP files');
        $this->assertGreaterThan(100, count($files), 'Should generate many PHP files');
    }

    public function testGeneratedFilesAreValidPHP(): void
    {
        if (!is_dir($this->generatedPath)) {
            $this->markTestSkipped('Generated directory does not exist. Run: php generate.php');
        }

        $files = glob($this->generatedPath . '/*.php');
        $this->assertNotEmpty($files, 'Should have files to test');

        // Test a sample of files
        $sampleFiles = array_slice($files, 0, 10);

        foreach ($sampleFiles as $file) {
            $content = file_get_contents($file);

            $this->assertStringStartsWith('<?php', $content, "File {$file} should start with PHP tag");
            $this->assertStringContainsString('namespace Plain\Generated', $content, "File {$file} should have correct namespace");
            $this->assertStringContainsString('declare(strict_types=1)', $content, "File {$file} should use strict types");

            // Test that the file has no syntax errors
            $syntaxCheck = exec("php -l " . escapeshellarg($file) . " 2>&1", $output, $returnCode);
            $this->assertEquals(0, $returnCode, "File {$file} should have valid PHP syntax: " . implode("\n", $output));
        }
    }

    public function testInputTypesAreGenerated(): void
    {
        if (!is_dir($this->generatedPath)) {
            $this->markTestSkipped('Generated directory does not exist. Run: php generate.php');
        }

        $expectedInputs = [
            'UpsertCustomerOnCreateInput.php',
            'UpsertCustomerOnUpdateInput.php',
            'CreateThreadInput.php',
            'AddCustomerToCustomerGroupsInput.php',
        ];

        foreach ($expectedInputs as $expectedInput) {
            $filePath = $this->generatedPath . '/' . $expectedInput;
            $this->assertFileExists($filePath, "Expected input type {$expectedInput} should be generated");

            $content = file_get_contents($filePath);
            $this->assertStringContainsString('final class', $content, "Input {$expectedInput} should be a final class");
            $this->assertStringContainsString('implements', $content, "Input {$expectedInput} should implement an interface");
        }
    }

    public function testGeneratedFilesHaveAutoGeneratedComment(): void
    {
        if (!is_dir($this->generatedPath)) {
            $this->markTestSkipped('Generated directory does not exist. Run: php generate.php');
        }

        $files = glob($this->generatedPath . '/*.php');
        $this->assertNotEmpty($files, 'Should have files to test');

        $sampleFile = $files[0];
        $content = file_get_contents($sampleFile);

        $this->assertStringContainsString('Auto-Generated', $content, 'Generated files should have auto-generated comment');
    }

    public function testGeneratedFilesUseReadonlyProperties(): void
    {
        if (!is_dir($this->generatedPath)) {
            $this->markTestSkipped('Generated directory does not exist. Run: php generate.php');
        }

        // Find a file that should have properties
        $inputFiles = glob($this->generatedPath . '/*Input.php');
        $this->assertNotEmpty($inputFiles, 'Should have input files to test');

        $sampleFile = $inputFiles[0];
        $content = file_get_contents($sampleFile);

        $this->assertStringContainsString('readonly', $content, 'Generated files should use readonly properties');
        $this->assertStringContainsString('private readonly', $content, 'Properties should be private readonly');
    }

    public function testDateTimeTypeIsMappedCorrectly(): void
    {
        if (!is_dir($this->generatedPath)) {
            $this->markTestSkipped('Generated directory does not exist. Run: php generate.php');
        }

        // Find files that might use DateTime
        $files = glob($this->generatedPath . '/*.php');
        $dateTimeFound = false;

        foreach ($files as $file) {
            $content = file_get_contents($file);
            if (strpos($content, 'DateTimeInterface') !== false) {
                $dateTimeFound = true;
                $this->assertStringContainsString('DateTimeInterface', $content, 'DateTime should be mapped to DateTimeInterface');
                break;
            }
        }

        if (!$dateTimeFound) {
            $this->markTestIncomplete('Could not find a file with DateTime type to verify mapping');
        }
    }
}
